[CmdletBinding()]
param(
  [switch]$SkipLean
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$RootDir = Split-Path -Parent $PSCommandPath
$DataDir = Join-Path $RootDir 'data'
$KbManagerDir = Join-Path $RootDir 'kb-manager'

function Find-Executable([string]$Name) {
  $command = Get-Command $Name -ErrorAction SilentlyContinue
  if ($command) {
    return $command.Source
  }
  return $null
}

function Find-Codex {
  $codex = Find-Executable 'codex'
  if ($codex) {
    return $codex
  }

  $extensionsRoot = Join-Path $env:USERPROFILE '.vscode\extensions'
  if (Test-Path $extensionsRoot) {
    return Get-ChildItem -Path $extensionsRoot -Filter 'codex.exe' -Recurse -ErrorAction SilentlyContinue |
      Sort-Object LastWriteTime -Descending |
      Select-Object -First 1 -ExpandProperty FullName
  }
  return $null
}

function Find-WinGetPackageExecutable([string]$FileName) {
  $packageRoot = Join-Path $env:LOCALAPPDATA 'Microsoft\WinGet\Packages'
  if (-not (Test-Path $packageRoot)) {
    return $null
  }
  return Get-ChildItem -Path $packageRoot -Filter $FileName -Recurse -ErrorAction SilentlyContinue |
    Select-Object -First 1 -ExpandProperty FullName
}

function Install-WinGetPackage([string]$Id) {
  $winget = Find-Executable 'winget'
  if (-not $winget) {
    throw "winget is required to install $Id automatically. Install it, then run setup.cmd again."
  }
  & $winget install --id $Id --exact --source winget `
    --accept-package-agreements --accept-source-agreements --disable-interactivity
  if ($LASTEXITCODE -ne 0) {
    throw "winget could not install $Id."
  }
}

function Ensure-DataLayout {
  foreach ($relativePath in @(
      'data', 'data\inbox', 'data\raw_sources', 'data\lean',
      'data\logs', 'data\wiki', 'data\workspace')) {
    $path = Join-Path $RootDir $relativePath
    if (-not (Test-Path $path)) {
      New-Item -ItemType Directory -Path $path -Force | Out-Null
    }
  }

  foreach ($relativePath in @(
      'data\download_queue.md', 'data\sources_manifest.md',
      'data\wiki\index.md', 'data\wiki\log.md')) {
    $path = Join-Path $RootDir $relativePath
    if (-not (Test-Path $path)) {
      New-Item -ItemType File -Path $path -Force | Out-Null
    }
  }
}

function Write-LocalConfiguration([string]$ComponentDirectory) {
  $envFile = Join-Path $ComponentDirectory '.env'
  if (Test-Path $envFile) {
    return
  }

  @(
    '# Generated by setup.ps1. Add API keys below only when you use external checks.',
    "KB_MANAGER_DIR=$($KbManagerDir -replace '\\', '/')",
    "DATA_DIR=$($DataDir -replace '\\', '/')",
    '',
    '# ANTHROPIC_API_KEY=',
    '# GEMINI_API_KEY=',
    '# OPENAI_API_KEY=',
    '# OPENROUTER_API_KEY='
  ) | Set-Content -LiteralPath $envFile -Encoding utf8
}

function Clear-StaleElanLocks {
  $toolchainDir = Join-Path $env:USERPROFILE '.elan\toolchains'
  if (-not (Test-Path $toolchainDir)) {
    return
  }

  foreach ($lock in Get-ChildItem -LiteralPath $toolchainDir -Filter '*.lock' -File) {
    $ownerPid = (Get-Content -LiteralPath $lock.FullName -Raw -ErrorAction SilentlyContinue).Trim()
    if ($ownerPid -match '^\d+$' -and -not (Get-Process -Id ([int]$ownerPid) -ErrorAction SilentlyContinue)) {
      Remove-Item -LiteralPath $lock.FullName -Force
      Write-Host "Removed stale Lean download lock: $($lock.Name)" -ForegroundColor DarkYellow
    }
  }
}

Ensure-DataLayout

$uv = Find-Executable 'uv'
if (-not $uv) {
  $uv = Find-WinGetPackageExecutable 'uv.exe'
}
if (-not $uv) {
  Write-Host 'Installing uv...' -ForegroundColor Cyan
  Install-WinGetPackage 'astral-sh.uv'
  $uv = Find-WinGetPackageExecutable 'uv.exe'
}
if (-not $uv) {
  throw 'uv was installed but could not be located. Open a new PowerShell window and run setup.cmd again.'
}

try {
  & $uv python find 3.14 | Out-Null
}
catch {
  Write-Host 'Installing official Python 3.14...' -ForegroundColor Cyan
  Install-WinGetPackage 'Python.Python.3.14'
}

& $uv python find 3.14 | Out-Null
if ($LASTEXITCODE -ne 0) {
  throw 'Python 3.14 installation could not be verified by uv.'
}

Write-Host 'Synchronizing the locked Python 3.14 environment...' -ForegroundColor Cyan
& $uv sync --all-packages --python 3.14 --locked
if ($LASTEXITCODE -ne 0) {
  throw 'uv failed to synchronize the workspace.'
}

Write-LocalConfiguration (Join-Path $RootDir 'nl-prover')
Write-LocalConfiguration (Join-Path $RootDir 'fl-prover')

if (-not $SkipLean) {
  $elan = Join-Path $env:USERPROFILE '.elan\bin\elan.exe'
  if (-not (Test-Path $elan)) {
    Write-Host 'Installing the Lean elan manager...' -ForegroundColor Cyan
    Install-WinGetPackage 'Lean.Elan'
    $elanInit = Find-WinGetPackageExecutable 'elan-init.exe'
    if (-not $elanInit) {
      throw 'elan was installed but elan-init.exe could not be located.'
    }
    & $elanInit -y --default-toolchain stable
    $elan = Join-Path $env:USERPROFILE '.elan\bin\elan.exe'
  }

  if (-not (Test-Path $elan)) {
    throw 'elan initialization did not complete.'
  }

  Clear-StaleElanLocks

  # A target Lean project with lean-toolchain takes precedence over this default.
  & $elan toolchain install stable
  & $elan default stable
  & $elan run stable lake --version
}

& $uv run python -c "import sys, sympy; print(f'Python {sys.version.split()[0]}; SymPy {sympy.__version__}')"
if ($LASTEXITCODE -ne 0) {
  throw 'The synchronized Python environment did not pass its import check.'
}

if (-not (Find-Codex)) {
  Write-Warning 'Codex CLI was not found. The deterministic tools are ready, but Codex sessions will need a Codex CLI installation.'
}

Write-Host ''
Write-Host 'Setup complete. Double-click start.cmd to choose an MMAT session.' -ForegroundColor Green
